// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// hsync //
// ----- //

#define hsync_wrap_target 1
#define hsync_wrap 8

static const uint16_t hsync_program_instructions[] = {
    0x80a0, //  0: pull   block                      
            //     .wrap_target
    0xa027, //  1: mov    x, osr                     
    0x0042, //  2: jmp    x--, 2                     
    0xff00, //  3: set    pins, 0                [31]
    0xff00, //  4: set    pins, 0                [31]
    0xff00, //  5: set    pins, 0                [31]
    0xff01, //  6: set    pins, 1                [31]
    0xec01, //  7: set    pins, 1                [12]
    0xc100, //  8: irq    nowait 0               [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hsync_program = {
    .instructions = hsync_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config hsync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hsync_wrap_target, offset + hsync_wrap);
    return c;
}

static inline void hsync_program_init(PIO pio, uint sm, uint offset, uint pin) {
    // creates state machine configuration object c, sets to default configuration.
    pio_sm_config c = hsync_program_get_default_config(offset);
    // Map the state machine's SET pin group to one pin, namely the `pin` parameter to this function.
    sm_config_set_set_pins(&c, pin, 1);
    // Set clock division.  Pico runs at 125MHz.  Diving by 5 runs this PIO at 25MHz.
    sm_config_set_clkdiv(&c, 5) ;
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
}

#endif

